language: node_js
node_js:
- node
cache:
  directories:
  - node_modules
script:
- npm i -D
- npm run build
deploy:
  provider: heroku
  api_key:
    secure: sTyM4D8dq9eAIoGCBPpoutTH2CwFlrd3Ehlw0XXmvqnTWWKlGgXTRITzJ70+kvwL892+I8nHMVbAjzdV6xCafvNKRS51sUtkCYK6G0jI5ewzO7C1naCHsGXLxvfBw/iZ20Xnq2vkmg1jRoWxoXvhRQrgbhayfc+4AB3gIdM4DzZcUtfR+svIrfLfpI9Q4hc2F3mrVl5RW/EzcngGYwSRLOe4+t9+/KBe+4GOC5tpdXcvepPh/k/Iqg0ZPz0Q0wd1yplCIb2Q7pTOLJciDwAIAN7MFZqnTtun+rUsW+6wcVi78aCzFTNidoz3MoIsMOAhxjpVz/RX8wX/Io4gdxFYKojFa7oeAN2OYMS7/ykq1DCOcMA+NfaJUlErcFCk6TY9BjcT0IQQ7GQ5gHQAJjzPRzb4CszgL40kK2a7FDky1ltDLioCsouLgeHVx9j6084T1UbV7kqFdVdVtVGxYkDr70IW5McPrNtr1cgSLBGb2MX7e/ivfixMcU8dIKtCI37yMBIoIeL99/TJfbQFGkdtiAJHYjbdTsEKfWdqNauuzsfUDXcaAyClu7A8VM4AfERtfEwDVelokQ97NXMNP6v3uRBpyJppJT8o17GNHNFmipiiBqZjGmhSDZi46hl7z0CMUV1iiqI5ffLR4wr8ieeg7MayjCtrq++m6sdLyooDZAU=
  name: repogit-github
  on:
    all_branches: true
