language: node_js
node_js:
  - node
cache:
  directories:
    - node_modules
script:
  - npm i -D
  - npm run build
deploy:
  provider: heroku
  api_key: "CzhhXYP+2s2H2+c4CVNYe7du/kbmwBWQYCBF3l+0cl04MDg/fmQ9uaVMPSLPUItgtBSMQYfoFv9aEkV33KEf5MgY8+JPLvJz+KtJpOkZ1kjPIbNjohZKWScIREemqq5OFU1d8DYEul7Nt9F3ryHVUNd7AB+QEahL45eXenrIPcdBDiwWJiYe5aVtF5FcSgjSu1A0CMFysr3i39mtv1494WWPq/MwdCAt0iyHexi7X5svGISPrJy/31CYigqFP8T0t31ZY6wMjPv8F8ddvJKW5SYq8p2scYa5ictbeLtx1LM04kynCs2m1TDtuKworcSk9a1MYtKKlToMgwdYajfVAfzA4Gy3tQRCftJ/8YgcAb3wxxlBxrQs25TMGIIKMifzWa/ot0ebiv7WMHilTabik9xrDp8BNDw7tWpQNfc35K0kbHC+N+4Sg3SlsYpkWcg5r0TfgydKMCg9F5R5Z56URM8gHZRwNiPlKj/CssfJ0YrCfwEsHRleIiN4A6NsRh4SA0aH3kgc67OEpMhMiJKcM7IaDygSheYlhILHMcHo2oSPvrZPIGvR9nK2H03VzB+TyxmP0jGKxMW90H1roY/B1DLX9gi3mNw5UsVNGF7K8JtGZr6E1t75pX4vP4vAppBYtdsO8dmv+7uEteay8wOB6KyW6BUTx3PMFghhnRPlEAI="
  name: repogit-github
  on:
    all_branches: true